# Generated by Django 6.0.6 on 2026-06-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('plot', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='movies', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
